#!name = 酷我音乐
#!desc = 解锁VIP(音质最高解锁至臻2.0)及去广告
#!author = 小白
#!date = 2024-11-13

[Script]

酷我音乐=type=http-response, pattern=^(?!.*img).*?kuwo\.cn(/vip|/openapi)?(/enc|/v[\d]/(user/vip\?(vers|apiVersion|platform|op\=ui|_t)|theme\?op=gd|sysinfo\?op=getRePayAndDoPayBoxNew|api(/pay)?/((user/personal/)?user/info|payInfo/kwplayer/payMiniBar|advert/(myPage|iListen|album))|album/(adBar|-myRec/vipMusic-))|/kuwopay/vip-tab/setting|/(audioApi/)?a\.p($|\?op\=getvip|.*?ptype\=vip)|/mobi\.s\?f\=kwxs|/music\.pay\?newver\=3$|/(EcomResource|(Mobile)?Ad)Serv(er|ice)), requires-body=1, script-path=https://js.chmg9999.top/kuwo1.js
[MITM]
hostname = %APPEND% *.kuwo.cn


